udp_bridge/remotes:
    robot:
        host: localhost
        port: 4200
        topics:
          project11_command: {source: project11/command}
          piloting_mode_manual_helm: {source: piloting_mode/manual/helm}
