udp_bridge/remotes:
    operator:
        host: localhost
        port: 4201
        topics:
          - source: sensors/gps/position
          - source: project11/heartbeat
          - source: project11/status/mission_manager
          - source: sensors/flir_engine
          - source: sensors/ais/contact
          - source: sensors/lidar/points
          - source: /diagnostics
          - source: nav/orientation
          - source: nav/position
          - source: nav/velocity
          - source: project11/response
          - source: sensors/radar
          - source: project11/display
          - source: mbr/9372/2510/margin_avg
          - source: mbr/9372/2510/margin_min
          - source: /tf
          - source: /tf_static
            
helm_manager/piloting_modes/active: ['manual', 'autonomous']
helm_manager/piloting_modes/standby: ['standby']
helm_manager/piloting_mode_prefix: 'piloting_mode/'
